# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ApplicationController::GeneratedPathHelpersModule; end
module ApplicationController::GeneratedUrlHelpersModule; end
module RecipeCategory::PrivateCollectionProxy; end
module RecipeIngredient::PrivateCollectionProxy; end
module T::Private::Methods::Signature; end
