# fly.toml app configuration file generated for cookpal on 2024-08-30T21:34:14+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cookpal'
primary_region = 'mad'
console_command = '/rails/bin/rails console'

[build]

[deploy]

[env]
  HOSTNAME = '0.0.0.0'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-2x'

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
