# fly.toml app configuration file generated for cookpal on 2024-08-31T00:18:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cookpal'
primary_region = 'mad'
console_command = '/rails/bin/rails console'

[build]

[deploy]

[env]
  HOSTNAME = '0.0.0.0'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = ''
  internal_port = 3000
  ports = []

[[vm]]
  size = 'shared-cpu-2x'
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
